apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: autojob-ingress
  namespace: autojob
spec:
  rules:
    - host: autojob.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: autojob-web
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: autojob-api
                port:
                  number: 8000

